# Generated by Django 5.0.1 on 2024-02-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car_Info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_info_model',
            name='battery_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car_info_model',
            name='fuel_efficiency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
