# Generated by Django 5.0.1 on 2024-02-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car_Info', '0002_alter_car_info_model_battery_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_info_model',
            name='battery_capacity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='car_info_model',
            name='fuel_efficiency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
